project_id = "ayqbpqgahtycrncbknvj"

[functions.ai-assistant]
verify_jwt = false

[functions.verify-certificate]
verify_jwt = false

[functions.create-student]
verify_jwt = false

[functions.ensure-student-onboarding]
verify_jwt = false

[functions.public-enrollment]
verify_jwt = false

[functions.approve-enrollment]
verify_jwt = false
