project_id = "ayqbpqgahtycrncbknvj"

[functions.ai-assistant]
verify_jwt = false

[functions.verify-certificate]
verify_jwt = false

[functions.create-student]
verify_jwt = false

[functions.ensure-student-onboarding]
verify_jwt = false

[functions.public-enrollment]
verify_jwt = false

[functions.approve-enrollment]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.student-enrollment-notify]
verify_jwt = false

[functions.uddoktapay-checkout]
verify_jwt = false

[functions.uddoktapay-verify]
verify_jwt = false

[functions.send-custom-email]
verify_jwt = false
